### ISSUE TITLE
Web 评论管理无法登陆

### ISSUE THREAD

**Issue by dongleizhang** [zhaojun1998/Valine-Admin#15]
我的 [Web 评论管理](https://banbanramble.leanapp.cn) 使用正确的管理员用户名密码无法登录了（使用账号密码登录会调回登录框），之前还是正常的，不知道什么原因，已经用你的最新 repo 部署了。其他邮件通知功能一切正常，都可以用。
<img width="435" alt="1" src="https://user-images.githubusercontent.com/19180725/45469000-1611b900-b75a-11e8-90ec-0998a3e85a5d.png">
<img width="765" alt="2" src="https://user-images.githubusercontent.com/19180725/45469001-17db7c80-b75a-11e8-903f-487c5bec6a4e.png">
<img width="1409" alt="3" src="https://user-images.githubusercontent.com/19180725/45469002-190ca980-b75a-11e8-82b9-cb947c963eca.png">
<img width="910" alt="4" src="https://user-images.githubusercontent.com/19180725/45469003-1ad66d00-b75a-11e8-919c-f43dfee60b31.png">

**Comment by zhaojun1998** [comment]
后台登录需要账号密码，需要在这里设置，只需要填写 email、password、username，这三个字段即可, 使用 email 作为账号登陆即可。**为了安全考虑，此 email 必须为配置中的 SMTP_USER 或 TO_EMAIL， 否则不允许登录**

README 中有写啊。
[README Web 评论管理 ](https://github.com/zhaojun1998/Valine-Admin/blob/master/%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE.md#web-评论管理)

**Comment by zhaojun1998** [comment]
@dongleizhang

**Comment by dongleizhang** [comment]
I see! 改成邮箱作为用户名就可以成功登录了。

是不是因为你最新的版本更改了设置，因为我之前用 存储 下面 _user 里有读写权限的账号 username 和密码是可以登录的。 @zhaojun1998

**Comment by zhaojun1998** [comment]
@dongleizhang 是的，因为当时有安全问题。
