### ISSUE TITLE
被回复人未收到邮件

### ISSUE THREAD

**Issue by Bill1987** [zhaojun1998/Valine-Admin#16]
您好，问一下，回复的评论，站长可以收到邮件，但是被@的人并没有收到邮件，
STDOUT web1 00:00:45 这条评论没有 @ 任何人
STDOUT web1 00:00:46 收到一条评论, 已提醒站长
Valine 版本 1.3.1
谢谢

**Comment by zhaojun1998** [comment]
@Bill1987 
1. 检查被 @ 人是否留了邮箱，如果他评论时没留邮箱，肯定是没法发的
2. 检查被 @ 人留的邮箱，是否是环境变量里的 `SMTP_USER` 或 `TO_EMAIL` 里的邮箱

**Comment by Bill1987** [comment]
都是我自己在测试，所以均填写了邮箱。而且是不同的。
具体情况如图：
![](https://i.loli.net/2018/09/24/5ba8dcc369889.jpg)
![](https://i.loli.net/2018/09/24/5ba8dce3544d7.jpg)
![](https://i.loli.net/2018/09/24/5ba8dcec3656f.jpg)
![](https://i.loli.net/2018/09/24/5ba8dcf1cf1dd.png)

**Comment by zhaojun1998** [comment]
我进你博客看了，你的 Valine 版本有问题啊，你这不是 Valine1.3.1 啊，你这不是 next 主题自带的 valine 吧

**Comment by zhaojun1998** [comment]
@Bill1987

**Comment by Bill1987** [comment]
嗯。我之前看你在别的里面说，1.3之前是有这个问题的，我就直接npm install valine --save 了一下。提示是1.3.1版本。但在我更新之前，也是不能收到的。我的操作是不是有什么问题啊。
另问一下怎么看valine当前版本是多少啊。。

**Comment by zhaojun1998** [comment]
npm install 不行吧，这个又不会改变 next 引用的版本，你肯定是修改了 next 的源码，恢复过来吧，然后看看 valine 的版本。

**Comment by Bill1987** [comment]
本地 Valine.min.js 文件中，显示
/*!
 * Valine v1.3.1
 * (c) 2017-2018 xCss
 * Released under the GPL-2.0 License.
 */

是我发布版本没更新上去吗？
网页上的代码，Valine版本 在哪看啊？

**Comment by zhaojun1998** [comment]
@Bill1987 应该是你没发布，或者本地有，但你没引用。

**Comment by Bill1987** [comment]
@zhaojun1998 十分感谢，此问题已经解决。

是的，我发布的版本并没有引用最新的v1.3.1

原因可能如下：
按照https://cloud.tencent.com/developer/article/1142490
配置的时候，有这样一步骤
`步骤一：下载 Valine.min.js 到文件夹 themes/next/source/js/src 下。`
问题应该就出在此文件上。

我把这个`Valine.min.js`文件指定成最新的版本后，该问题解决。
可能是我做错了，或者遗漏了某些步骤吧。

再次感谢您的耐心解答，谢谢！

**Comment by zhaojun1998** [comment]
@Bill1987 解决了就好。
