### ISSUE TITLE
能否自定义收件人

### ISSUE THREAD

**Issue by AlliotTech** [zhaojun1998/Valine-Admin#19]
感谢owner提供好项目，有个问题就是，能否单独设置站长收信邮箱，即 分开设置 发件邮箱 与 站长收件邮箱

**Comment by zhaojun1998** [comment]
@AlliotTech  有啊。README 里也有写的：[自定义收件邮箱](https://github.com/zhaojun1998/Valine-Admin/blob/master/%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%94%B6%E4%BB%B6%E9%82%AE%E7%AE%B1)
