### ISSUE TITLE
QQ和QQex应该填哪个

### ISSUE THREAD

**Issue by DereenMec** [zhaojun1998/Valine-Admin#20]
https://nodemailer.com/smtp/well-known/#supported-services

这里有一个QQ和一个QQex，QQ邮箱应该填哪个？？

**Comment by zhaojun1998** [comment]
@DereenMec 你是普通 qq 邮箱就填 qq

**Comment by DereenMec** [comment]
> @DereenMec 你是普通 qq 邮箱就填 qq

oK,thank you

**Comment by zhaojun1998** [comment]
@DereenMec 你应该先确保你可以正常收到通知邮件

**Comment by DereenMec** [comment]
> @DereenMec 你应该先确保你可以正常收到通知邮件

OK,没问题的，可以收到邮件了

**Comment by zhaojun1998** [comment]
@DereenMec 定时器已加。
