### ISSUE TITLE
部署完在user表添加了登录不了

### ISSUE THREAD

**Issue by fjcqv** [zhaojun1998/Valine-Admin#6]
部署完在user表添加了登录不了？

**Comment by ZvonimirSun** [comment]
设置密码了没

**Comment by ZvonimirSun** [comment]
我看了下代码，要用邮箱加密码登录，而且邮箱需要是你设置的环境变量里的一个，就是那个smtp_user和to_mail。

fjcqv <notifications@github.com> 于 2018年7月8日周日 08:21写道：

**Comment by fjcqv** [comment]
用邮箱可以了，谢谢~
