### ISSUE TITLE
站长回复评论者站长也会收到通知

### ISSUE THREAD

**Issue by kzw200015** [zhaojun1998/Valine-Admin#7]
如题，我感觉这没什么必要啊，希望能改善一下

**Comment by zhaojun1998** [comment]
@kzw200015 
好的，将会在下个版本中加入配置项，来支持此功能，预计明天下午更新。

十分抱歉，之前因为工作原因，没有注意到该 `issue`。

**Comment by zhaojun1998** [comment]
@kzw200015 已修改。
